name: AnimatedDoors
version: '${project.version}'
main: com.coffeepng.animateddoors.AnimatedDoorsPlugin
api-version: '1.21'
description: Usable animated doors triggered by redstone or floating click-triggers.
author: coffeepng
commands:
  door:
    description: Create and control animated doors.
    usage: /door help
    aliases: [adoor, animateddoor]
    permission: animateddoors.use
permissions:
  animateddoors.use:
    description: Base permission to use AnimatedDoors commands.
    default: op
  animateddoors.admin:
    description: Create, edit and remove doors.
    default: op
    children:
      animateddoors.use: true
  animateddoors.toggle:
    description: Toggle doors via triggers / clicking.
    default: true
